terminals = {
    "L": r"[a-z][a-z]*",
    "N": r"[0-9]+",
    "TP": r"(int|string)",
    "IN": r"var",
    "IG": r"=",
    "PA": r"\(",
    "PC": r"\)",
    "CO": r"\,",
    "FN": r"\;",
    "F": r"funn",
    "F2": r"Funn",
    "C": r"contenido",
    "LA": r"\{",
    "LC": r"\}",
    "IF": r"si",
    "CON": r"<",
    "MAS": r"\+",
    "E": r"sino",
    "RE": r"repite",
    "DD": r"desde",
    "HA": r"hasta",
    "MN": r"Inn",
    "RT": r"return",
    "Q": r"$"
}